FROM local-qwen3-tts:latest  

RUN apt-get update && apt-get install -y \
    git \    
    build-essential \
    libsndfile1 \
    sqlite3 \
    sox \
    libsox-fmt-all \
    libportaudio2 \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY requirements.txt .
RUN pip install torchaudio

RUN rm -rf /app/Qwen3-TTS-streaming
RUN git clone https://github.com/rekuenkdr/Qwen3-TTS-streaming.git

WORKDIR /app/Qwen3-TTS-streaming
RUN pwd
RUN pip install -e .

#COPY . .

EXPOSE 8008
CMD ["pwd"]
#CMD ["python", "voice_server.py"]